name: Draft release from PR

on:
  pull_request_target:
    types:
      - closed
    branches:
      - stable
      - minor-next
      - major-next
      - "legacy/*"
    paths:
      - "src/VersionInfo.php"

jobs:
  check-validity:
    name: Check that this PR merge is a valid release target
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        php-version: [8.2]

    outputs:
      valid: ${{ steps.validate.outputs.VALID_RELEASE == 'true' 
          && steps.check-permission.outputs.require-result == 'true'
          && steps.check-permission.outputs.check-result == 'false'
        }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@2.31.1
        with:
          php-version: ${{ matrix.php-version }}

      - name: Restore Composer package cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/composer/files
            ~/.cache/composer/vcs
          key: "composer-v2-cache-${{ hashFiles('./composer.lock') }}"
          restore-keys: |
            composer-v2-cache-

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --ignore-platform-reqs

      - name: Check if PR author has write access
        id: check-permission
        uses: actions-cool/check-user-permission@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          require: write
          username: ${{ github.event.pull_request.user.login }}
          #technically this would be fine for dependabot but generally bots don't count as team members
          check-bot: true

      - name: Check IS_DEVELOPMENT_BUILD flag
        id: validate
        run: |
          echo VALID_RELEASE=$(php -r 'require "vendor/autoload.php"; echo \pocketmine\VersionInfo::IS_DEVELOPMENT_BUILD ? "false" : "true";') >> $GITHUB_OUTPUT

  draft:
    name: Create GitHub draft release
    needs: [check-validity]
    if: needs.check-validity.outputs.valid == 'true'

    uses: ./.github/workflows/draft-release.yml
